// web/src/routes/playlists/+page.svelte
<script lang="ts">
  // TODO: Update details for mobile

  let LIMIT = 5;

  import type { SpotifyPlaylist } from '$lib/spotify/spotify';
  import DotHead from '$lib/components/util/DotHead.svelte';
  import { NUMS } from '../../constants';
  import Head from '$lib/components/util/Head.svelte';

  let itemOpen: number | null = null;

  function handleOpen(index: number) {
    if (index === itemOpen) itemOpen = null;
    else itemOpen = index;
  }

  export let data: { playlists: SpotifyPlaylist[] };
</script>

<Head pageTitle="Playlists" route="playlists" />

{#each data.playlists as { name, tracks, image, date, href, duration }, playlistIndex}
  {@const isActive = playlistIndex === itemOpen}

  <section>
    <div ">
      <img src={image} alt={name}  />
      <h2>{name}</h2>
    </div>

    <div>
      <div><DotHead>{date}</DotHead></div>
      <div><DotHead>DUR {duration}</DotHead></div>
      <div>
        <a {href} target="_blank"><DotHead>LINK ↗</DotHead></a>
      </div>
    </div>

    <ul>
      {#each tracks as { name, duration, artists }, i}
        <li class:hidden={i + 1 > LIMIT && !isActive}>
          {NUMS[i + 1]}
          {name}&mdash;{artists.join(' & ')} ({duration}){' '}
        </li>
      {/each}
    </ul>

    <button on:click={() => handleOpen(playlistIndex)}>
      <DotHead>{isActive ? 'See Less ↑' : 'See All ↓'}</DotHead>
    </button>
  </section>
{/each}

// src/pageTemplates/Playlists/Playlists.tsx
import React, { useState } from "react"
import { ISpotifyPlaylist, IParsedTrack } from "types/spotify"
import { Wrapper, LargeHead } from "components"
import parseSpotify from "util/parseSpotify"
import { NUMBERS, UNICODE } from "../../constants"
import S from "./Playlists.Styled"

const { UP, DOWN, CIRCLE, NE } = UNICODE

interface IProps {
  data: ISpotifyPlaylist[]
}

const LIMIT = 5

const Playlists: React.FC<IProps> = ({ data }) => {
  return (
    <div>
      {data.map(pl => (
        <Playlist data={pl} key={pl.name} />
      ))}
    </div>
  )
}

interface IPlaylistProps {
  data: ISpotifyPlaylist
}

const Playlist: React.FC<IPlaylistProps> = ({ data }) => {
  const { totalDuration, tracks, img, dateCreated, link } = parseSpotify(data)
  const [isLimit, setLimit] = useState<boolean>(true)
  const limitedTracks = isLimit ? [...tracks].slice(0, LIMIT) : tracks

  return (
    <div>
      <S.Playlist>
        <Wrapper>
          <S.TitleBlock>
            <LargeHead>
              <img src={img} alt="" />
            </LargeHead>
            <LargeHead>{data.name}</LargeHead>
          </S.TitleBlock>
        </Wrapper>

        <S.Metadata>
          <S.MetadataItem>
            {CIRCLE} {dateCreated}
          </S.MetadataItem>
          <S.MetadataItem>
            {CIRCLE} DUR {totalDuration}
          </S.MetadataItem>
          <S.MetadataItem>
            <a href={link} target="_blank" rel="noopener noreferrer">
              {CIRCLE} LINK {NE}
            </a>
          </S.MetadataItem>
        </S.Metadata>

        <Wrapper>
          <S.TracksWrapper>
            {limitedTracks.map(({ title, artist, duration }, i) => {
              return (
                <Track
                  key={title}
                  number={NUMBERS[i + 1]}
                  title={title}
                  artist={artist}
                  duration={duration}
                />
              )
            })}
          </S.TracksWrapper>
        </Wrapper>

        <S.Metadata>
          <S.MetadataItem>
            {isLimit ? (
              <span onClick={() => setLimit(false)}>
                {CIRCLE} See All {DOWN}
              </span>
            ) : (
              <span onClick={() => setLimit(true)}>
                {CIRCLE} See Less {UP}
              </span>
            )}
          </S.MetadataItem>
        </S.Metadata>
      </S.Playlist>
    </div>
  )
}

interface ITrackProps extends IParsedTrack {
  number: string
}

const Track: React.FC<ITrackProps> = ({ number, title, artist, duration }) => {
  return (
    <span>
      {number} {title}—{artist} ({duration}){" "}
    </span>
  )
}

export default Playlists
