// web/src/routes/info/+page.svelte
<script lang="ts">
	import { EMAIL, LINK_EMAIL, LINK_IG, NUMS, IG } from '../../constants';
	import { DotHead } from '$components';
	import { formatTime } from '$util/msToTime';

	let { data } = $props();
	let { bio, clients, playlists } = $derived(data.infoPage);
</script>

<section class="my-large">
	<div class="wrapper my-medium">
		<h2><DotHead>Bio</DotHead></h2>
		<h1 class="text-h1">{bio}</h1>
	</div>

	<div class="wrapper my-medium grid grid-cols-6">
		<div class="col-span-6 md:col-span-3">
			<div>
				<h3 class="inline"><DotHead noMarginBottom>E-M &rarr;</DotHead></h3>
				<a class="underline" href={LINK_EMAIL}>{EMAIL}</a>
			</div>

			<div>
				<h3 class="inline"><DotHead noMarginBottom>IG &rarr;</DotHead></h3>
				<a class="underline" href={LINK_IG}>{IG}</a>
			</div>
		</div>

		{#if clients?.length}
			<div class="col-span-6 md:col-span-3">
				<h2><DotHead>Clients</DotHead></h2>

				<ul class="gap-standard columns-2">
					{#each clients as client}<li>{client}</li>{/each}
				</ul>
			</div>
		{/if}
	</div>
</section>

<hr />

<section class="my-large">
	<div class="wrapper my-medium">
		{#if data.nowPlaying}
			{@const { trackName, artist, nowPlaying } = data.nowPlaying}
			<h2>
				<DotHead>{nowPlaying ? 'Now Playing' : 'Recently Played'}</DotHead>
			</h2>
			<h3 class="text-h1">
				{#if nowPlaying}
					Right now I'm listening to “{trackName}” by {artist} on Spotify.
				{:else}
					The last song I listened to on Spotify was “{trackName}” by {artist}.
				{/if}
			</h3>
		{/if}
	</div>

	<div class="wrapper my-medium">
		<h2><DotHead>Featured playlists</DotHead></h2>

		<ul class="mb-4 leading-[1.3]">
			{#each playlists || [] as { link, title, duration, date }, i}
				<li>
					<a
						href={link}
						target="_blank"
						class="gap-standard flex grid-cols-6 justify-between md:grid"
					>
						<div class="col-span-4 flex gap-2 md:col-span-2">
							<span>{NUMS[i + 1]}</span>
							<h3 class="max-w-[18ch]">{title}</h3>
						</div>
						<p class="col-span-2 hidden md:block">{date}</p>
						<p class="gap-standard col-span-2 flex justify-between">
							{formatTime(duration || 0, 'hh:mm:ss')}<span>&rarr;</span>
						</p>
					</a>
				</li>
			{/each}
		</ul>

		<a href="/playlists" class="underline">See all playlists &rarr;</a>
	</div>
</section>

// src/components/Info/Info.tsx
import React from "react"
import { DotHead, Grid, LargeHead } from "components"
import { IInfoRes } from "types/Prismic"
import { RichText } from "util/richText"
import useNowPlaying from "hooks/useNowPlaying"
import { IParsedPlaylist } from "types/SpotifyPlaylist"
import Link from "next/link"
import S from "./Info.Styled"
import { NUMBERS, UNICODE } from "../../constants"

const Info: React.FC<{
  data: IInfoRes
  playlistData: IParsedPlaylist[]
}> = ({ data: res, playlistData }) => {
  const { clients, introduction } = res.results[0].data

  return (
    <>
      <S.LgSection>
        <S.Section>
          <div>
            <DotHead>Bio</DotHead>
            <LargeHead>
              <RichText>{introduction}</RichText>
            </LargeHead>
          </div>
        </S.Section>
        <S.Section>
          <Contact />
          <S.TwoCol>
            <DotHead>Clients</DotHead>
            <ul>
              {clients.split(/\n/).map(item => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </S.TwoCol>
        </S.Section>
      </S.LgSection>
      <S.Hr />
      <S.LgSection>
        <Music />
        <FeaturedPlaylists data={playlistData} />
      </S.LgSection>
    </>
  )
}

const Contact = () => (
  <S.TwoCol>
    <div>
      &#9679; E-M→{" "}
      <a href="mailto:hello@tylermcrobert.com">hello@tylermcrobert.com</a>
    </div>
    <div>
      &#9679; IG→{" "}
      <a href="http://instagram.com/tylermcrobert">@tylermcrobert</a>{" "}
    </div>
  </S.TwoCol>
)

const Music = () => {
  const { loading, artist, trackName, nowPlaying } = useNowPlaying()

  return (
    <S.Section>
      <div>
        {!loading && !!artist && (
          <>
            <DotHead>{nowPlaying ? "Now Playing" : "Recently Played"}</DotHead>
            <LargeHead>
              {nowPlaying ? (
                <>
                  Right now I&apos;m listening to:&nbsp;“{trackName}” by{" "}
                  {artist} on Spotify.
                </>
              ) : (
                <>
                  The last song I listened to on Spotify was &nbsp;“{trackName}”
                  by {artist}.
                </>
              )}
            </LargeHead>
          </>
        )}
      </div>
    </S.Section>
  )
}

const FeaturedPlaylists: React.FC<{
  data: IParsedPlaylist[]
}> = ({ data }) => {
  return (
    <S.Section>
      <div>
        <div>
          <DotHead>Featured Playlists</DotHead>
        </div>

        {data.map((item, i) => (
          <S.PlaylistWrapper
            key={item.name}
            href={item.link}
            target="_blank"
            rel="noopener noreferrer"
          >
            <p>
              {NUMBERS[i + 1]} {item.name}
            </p>
            <p>{item.dateCreated}</p>
            <p>{item.totalDuration}</p>
            <p> {UNICODE.RIGHT}</p>
          </S.PlaylistWrapper>
        ))}
      </div>
      <Link href="/playlists">
        <a>See all playlists {UNICODE.RIGHT}</a>
      </Link>
    </S.Section>
  )
}

export default Info
