// web/src/components/Modules/Modules.svelte
<script lang="ts">
	import ModuleMobileWebsite from '$components/ModuleMobileWebsite.svelte';
	import { sanityDataAttribute } from '$lib/attachments';
	import type { Module } from '$sanity';

	import ModuleContext from './ModuleContext.svelte';
	import ModuleDiptych from './ModuleDiptych.svelte';
	import MediaBlock from './ModuleMediaBlock.svelte';
	import ModulePlaylistBlock from './ModulePlaylistBlock.svelte';
	import TextBlock from './ModuleTextBlock.svelte';
	import ModuleTimedSlides from './ModuleTimedSlides.svelte';
	import ModuleTripleImage from './ModuleTripleImage.svelte';
	import ModuleWebsite from './ModuleWebsite.svelte';

	type Props = {
		modules: Module[];
		documentId: string;
		documentType: string;
	};

	let { modules, documentId, documentType }: Props = $props();
</script>

<div class="wrapper mx-auto">
	{#each modules as data, index}
		{@const path = `modules[_key=="${data._key}"]`}

		<ModuleContext {index} {documentId} {documentType} {path}>
			<section data-type={data._type} {@attach sanityDataAttribute()}>
				{#if data._type === 'textBlock'}
					<TextBlock {data} />
				{:else if data._type === 'mediaBlock'}
					<MediaBlock {data} />
				{:else if data._type === 'website'}
					<ModuleWebsite {data} />
				{:else if data._type === 'diptych'}
					<ModuleDiptych {data} />
				{:else if data._type === 'tripleImage'}
					<ModuleTripleImage {data} />
				{:else if data._type === 'mobileWebsite'}
					<ModuleMobileWebsite {data} />
				{:else if data._type === 'timedSlides'}
					<ModuleTimedSlides {data} />
				{:else if data._type === 'playlistBlock'}
					<ModulePlaylistBlock {data} />
				{:else}
					{console.warn('Cannot find module:', data._type)}
				{/if}
			</section>
		</ModuleContext>
	{/each}
</div>

// src/components/Modules/Modules.tsx
import React from 'react'
import { useCaseStudy } from 'hooks'
import {
  ModuleSingleImage,
  ModuleDoubleImage,
  ModuleTripleImage,
  Grid,
  ModuleWebsite,
  ModuleText,
  ModuleDynamicImage,
  ModuleSpacer,
  ModuleMobileWebsite,
  ModuleTimedSlides,
} from 'components'

const Modules = () => {
  const { modules } = useCaseStudy()

  return (
    <Grid>
      {(modules || []).map(module => {
        switch (module._type) {
          case 'singleImage':
            return <ModuleSingleImage key={module._key} data={module} />
          case 'doubleImage':
            return <ModuleDoubleImage key={module._key} data={module} />
          case 'tripleImage':
            return <ModuleTripleImage key={module._key} data={module} />
          case 'website':
            return <ModuleWebsite key={module._key} data={module} />
          case 'textBlock':
            return <ModuleText key={module._key} data={module} />
          case 'dynamicImage':
            return <ModuleDynamicImage key={module._key} data={module} />
          case 'spacer':
            return <ModuleSpacer key={module._key} data={module} />
          case 'mobileWebsite':
            return <ModuleMobileWebsite key={module._key} data={module} />
          case 'timedSlides':
            return <ModuleTimedSlides key={module._key} data={module} />
          default:
            return null
        }
      })}
    </Grid>
  )
}

export default Modules
