// web/src/lib/components/portfolioModules/ModuleWebsite.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import ResponsiveImage from '../ResponsiveImage.svelte';
  import type { ModuleWebsite } from '$lib/sanity/queries';
  import BrowserFrame from '$lib/components/util/BrowserFrame.svelte';
  export let data: ModuleWebsite;

  $: ({ media, showFrame, backgroundImg, theme } = data);
</script>

<div style={`background:${theme?.background || ''}`}>
  {#if backgroundImg}
    <div>
      <ResponsiveImage
        image={backgroundImg}
        alt={$page.data.title}
        sizes="90vw"
        aspect={1.5}
      />
    </div>
  {/if}

  <div>
    {#if showFrame !== false && theme?.frame}
      <BrowserFrame color={theme?.frame} dotColor={theme.dots} />
    {/if}

    {#if media?.image?.asset}
      <ResponsiveImage
        color="#ffffff"
        image={media.image}
        alt={$page.data.title}
        sizes="80vw"
      />
    {:else if media?.video}
      <video src={media.video} muted playsinline loop autoplay />
    {/if}
  </div>
</div>

// src/components/ModuleWebsite/ModuleWebsite.tsx
import React from 'react'
import S from './ModuleWebsite.Styled'
import BrowserFrame from './Browserframe'
import { ModuleWebsite } from 'types'
import getResponsiveImgProps from 'util/getResponsiveImgProps'

interface IProps {
  data: ModuleWebsite
}

const Website: React.FC<IProps> = ({ data }) => {
  const {
    media: mediaArr,
    theme: { frame, background, dots },
  } = data

  const media = mediaArr[0]

  return (
    <S.BrowserBackground backgroundColor={background.hex}>
      <S.Browser>
        <div>
          <BrowserFrame color={frame.hex} dots={dots?.hex} />
          {media._type === 'image' && (
            <img
              {...getResponsiveImgProps({ img: media, sizes: { xxs: '90vw' } })}
              alt=""
            />
          )}
          {/* {media && media.url && (
            <video autoPlay muted playsInline loop>
              <source src={media.url} />
            </video>
          )} */}
        </div>
      </S.Browser>
    </S.BrowserBackground>
  )
}

export default Website
