// web/src/components/Modules/ModuleWebsite.svelte
<script lang="ts">
	import { createContext } from 'svelte';
	import BrowserFrame from '$components/BrowserFrame.svelte';
	import Image from '$components/Image.svelte';
	import Media from '$components/Media.svelte';
	import type { ModuleWebsite } from '$sanity';
	import { colorToString } from '$util/colorToRgba';
	import { setContext } from 'svelte';

	type Props = { data: ModuleWebsite };

	let { data }: Props = $props();
	let { showFrame, backgroundImg, media } = $derived(data);
</script>

<div
	style:background={data.backgroundColor || "var(--browser-section-background)"}
	class="relative my-standard w-full bg-black p-[10%]"
>
	<div class="relative z-10">
		{#if showFrame !== false}
			<BrowserFrame />
		{/if}

		{#if media?.asset}
			<div class="bg-white">
				<Media sizes="80vw" value={media.asset} alt={null} />
			</div>
		{/if}
	</div>

	{#if backgroundImg}
		<div>
			<Image
				image={backgroundImg}
				alt={null}
				sizes="90vw"
				aspect={1.5}
				class="absolute inset-0 z-0 h-full w-full object-cover"
			/>
		</div>
	{/if}
</div>

// src/components/ModuleWebsite/ModuleWebsite.tsx
import React from 'react'
import S from './ModuleWebsite.Styled'
import BrowserFrame from './Browserframe'
import { ModuleWebsite, WebsiteMedia } from 'types'
import getResponsiveImgProps from 'util/getResponsiveImgProps'
import { ViewportVideo } from 'components'

interface IProps {
  data: ModuleWebsite
}

const Website: React.FC<IProps> = ({ data }) => {
  const { media: mediaArr, theme } = data
  const media = mediaArr && mediaArr[0]
  const isFrameVisible = data.showFrame === undefined ? true : data.showFrame

  return (
    <S.BrowserBackground backgroundColor={theme?.background?.hex}>
      <S.Browser>
        {data.backgroundImg && (
          <S.BackgroundImage
            alt="background image"
            {...getResponsiveImgProps({
              img: data.backgroundImg,
              sizes: { xxs: '100vw' },
              aspect: 2 / 3,
            })}
          />
        )}
        <S.Content>
          {isFrameVisible && (
            <BrowserFrame color={theme?.frame?.hex} dots={theme?.dots?.hex} />
          )}
          {media && <Media data={media} />}
        </S.Content>
      </S.Browser>
    </S.BrowserBackground>
  )
}

export const Media: React.FC<{ data: WebsiteMedia }> = ({ data: media }) => {
  const videoUrl = (media?._type === 'video' && media.video?.url) || null

  return (
    <>
      {media?._type === 'image' && (
        <img
          {...getResponsiveImgProps({
            img: media,
            sizes: { xxs: '90vw' },
          })}
          alt=""
        />
      )}
      {videoUrl && <ViewportVideo src={videoUrl} />}
    </>
  )
}

export default Website
