// web/src/lib/components/portfolioModules/ModuleDynamicImage.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import ResponsiveImage from '../ResponsiveImage.svelte';
  import type { ModuleDynamicImage } from '$lib/sanity/queries';

  export let data: ModuleDynamicImage;

  $: half = data.span === 'half';
  $: full = !half;
</script>

<div class:half class:full>
  {#if data.image?.asset}
    <ResponsiveImage
      image={data.image}
      alt={$page.data.title}
      aspect={(data.aspect && 1 / data.aspect) || undefined}
      sizes={half ? '50vw' : '100vw'}
    />
  {/if}
</div>

// src/components/ModuleDynamicImage/ModuleDynamicImage.tsx
import React from 'react'
import { ModuleDynamicImage } from 'types'
import { useCaseStudy } from 'hooks'
import getResponsiveImgProps from 'util/getResponsiveImgProps'
import S from './ModuleDynamicImage.Styled'

const DynamicImage: React.FC<{ data: ModuleDynamicImage }> = ({ data }) => {
  const isHalf = data.span === 'half'
  const { alt } = useCaseStudy()

  return data.image ? (
    <S.Img
      isHalf={isHalf}
      {...getResponsiveImgProps({
        img: data.image,
        aspect: data.aspect,
        sizes: {
          xxs: '100vw',
          sm: isHalf ? '50vw' : '100vw',
        },
      })}
      alt={alt}
    />
  ) : null
}

export default DynamicImage
