// web/src/lib/PortfolioModules/ModuleDynamicImage.svelte
<script lang="ts">
  import ResponsiveImage from '$lib/ResponsiveImage.svelte';
  import type { ModuleDynamicImage } from '$lib/sanity/queries';
  export let data: ModuleDynamicImage;

  let half = data.span === 'half';
  let full = data.span === 'full';
</script>

<div class="img" class:half class:full>
  <ResponsiveImage
    image={data.image}
    alt=""
    sizes={half ? '50vw' : '100vw'}
    aspect={data.aspect}
  />
</div>

<style>
  .img :global(img) {
    max-width: 100%;
  }
</style>

// src/components/ModuleDynamicImage/ModuleDynamicImage.tsx
import React from 'react'
import { ModuleDynamicImage } from 'types'
import { useCaseStudy } from 'hooks'
import getResponsiveImgProps from 'util/getResponsiveImgProps'
import S from './ModuleDynamicImage.Styled'

const DynamicImage: React.FC<{ data: ModuleDynamicImage }> = ({ data }) => {
  const isHalf = data.span === 'half'
  const { alt } = useCaseStudy()

  return data.image ? (
    <S.Img
      isHalf={isHalf}
      {...getResponsiveImgProps({
        img: data.image,
        aspect: data.aspect,
        sizes: {
          xxs: '100vw',
          sm: isHalf ? '50vw' : '100vw',
        },
      })}
      alt={alt}
    />
  ) : null
}

export default DynamicImage
