// src/components/Modules/Modules.tsx
import React from 'react'
import { useCaseStudy } from 'hooks'
import {
  ModuleSingleImage,
  ModuleDoubleImage,
  ModuleTripleImage,
  Grid,
  ModuleWebsite,
  ModuleText,
  ModuleDynamicImage,
  ModuleSpacer,
  ModuleMobileWebsite,
  ModuleTimedSlides,
} from 'components'

const Modules = () => {
  const { modules } = useCaseStudy()

  return (
    <Grid>
      {(modules || []).map(module => {
        switch (module._type) {
          case 'singleImage':
            return <ModuleSingleImage key={module._key} data={module} />
          case 'doubleImage':
            return <ModuleDoubleImage key={module._key} data={module} />
          case 'tripleImage':
            return <ModuleTripleImage key={module._key} data={module} />
          case 'website':
            return <ModuleWebsite key={module._key} data={module} />
          case 'textBlock':
            return <ModuleText key={module._key} data={module} />
          case 'dynamicImage':
            return <ModuleDynamicImage key={module._key} data={module} />
          case 'spacer':
            return <ModuleSpacer key={module._key} data={module} />
          case 'mobileWebsite':
            return <ModuleMobileWebsite key={module._key} data={module} />
          case 'timedSlides':
            return <ModuleTimedSlides key={module._key} data={module} />
          default:
            return null
        }
      })}
    </Grid>
  )
}

export default Modules

// web/src/lib/components/Modules.svelte
<script lang="ts">
  import ModuleDynamicImage from './portfolioModules/ModuleDynamicImage.svelte';
  import ModuleWebsite from './portfolioModules//ModuleWebsite.svelte';
  import type { PortfolioModule } from '$lib/sanity/queries';
  import ModuleTextBlock from './portfolioModules/ModuleTextBlock.svelte';
  import ModuleMobileWebsite from './portfolioModules/ModuleMobileWebsite.svelte';
  import ModuleTimedSlides from './portfolioModules/ModuleTimedSlides.svelte';
  import ModuleTripleImage from './portfolioModules/ModuleTripleImage.svelte';
  import ModuleEmptySpace from './portfolioModules/ModuleEmptySpace.svelte';

  export let modules: PortfolioModule[];
</script>

{#each modules as module}
  {#if module._type === 'website'}
    <ModuleWebsite data={module} />
  {:else if module._type === 'dynamicImage'}
    <ModuleDynamicImage data={module} />
  {:else if module._type === 'tripleImage'}
    <ModuleTripleImage data={module} />
  {:else if module._type === 'textBlock'}
    <ModuleTextBlock data={module} />
  {:else if module._type === 'mobileWebsite'}
    <ModuleMobileWebsite data={module} />
  {:else if module._type === 'timedSlides'}
    <ModuleTimedSlides data={module} />
  {:else if module._type === 'emptySpace'}
    <ModuleEmptySpace />
  {/if}
{/each}
